# Generated by Django 3.1.6 on 2021-02-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
