# Generated by Django 3.1.6 on 2021-02-17 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note_system', '0005_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='NoteItem',
        ),
    ]
