# Generated by Django 3.1.6 on 2021-02-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_system', '0006_auto_20210217_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
